### ISSUE TITLE
Preserve parameter names

### ISSUE THREAD

**Issue by cbruegg** [soot-oss/SootUp#204]
**TODO**
- [ ] make it an ClassLoadingOption
- [ ] adapt JavaBytecodeFrontend to use `LocalGenerator`
- [ ] make it an `ByteCodeClassLoadingOption`
- [ ] consider preserving names of other Variables/Locals, too

Both frontends currently don't preserve method parameter names in the generated Jimple. The branch [feature/preserve-param-names](https://github.com/secure-software-engineering/soot-reloaded/compare/feature/preserve-param-names) shows how the names can be preserved both for bytecode and for source code. They name the body locals according to the parameter names.

```java
void foo(int aNumber) {
  ...
}
```

For the method above, this results in the following Jimple:

```
aNumber := @parameter0: int;
```

However, there are two issues that still need to be resolved in this branch:

First, there may be clashes if a parameter has a name that would also be generated by `LocalGenerator`. For instance, I believe the following Java snippet would result in Jimple with local variable name clashes:

```java
void foo(int $i0) {
  int anotherInt = 0;
}
```

Second, there are a lot of failing tests because the variable names don't match anymore. These need to be corrected.

**Comment by swissiety** [comment]
duplicate #780 #875
