### ISSUE TITLE
Support Multi-Release Jar files

### ISSUE THREAD

**Issue by anddann** [soot-oss/SootUp#50]
resources:
https://www.javaworld.com/article/3184029/java-language/java-9s-other-new-enhancements-part-4-multi-release-jar-files.html
https://www.baeldung.com/java-multi-release-jar

## TODO
depends on #185 (java9 module loading)
 
### Parameter: newest supported Java Version
- [ ] ignore java versions <9 (according to spec) 
- [ ] select newest version lower equals given parameter down to base version 

### nice2have:
- [ ] list existing version variants of a module
- [ ] above list merged across all user specified modules
